CREATE TABLE cakes (id INTEGER PRIMARY KEY, flavor TEXT, egg TEXT ,quantity_in_kgs INTEGER, price INTEGER) ;
INSERT INTO cakes VALUES (1, "Bananas", "NO", 1, 250);
INSERT INTO cakes VALUES(2, "Peanut Butter", "yes", 3, 600);
INSERT INTO cakes VALUES(3, "vanilla", "yes", 5, 380);
INSERT INTO cakes VALUES(4, "Ice cream", "yes", 3, 250);
INSERT INTO cakes VALUES(5, "berries", "no",1, 800);
INSERT INTO cakes VALUES(6, "Chocolate", "yes",3, 250);
INSERT INTO cakes VALUES (7, "rose", "NO", 1, 250);
INSERT INTO cakes VALUES(8, "white forest", "yes", 3, 600);
INSERT INTO cakes VALUES(9, "coconut", "yes", 5, 380);
INSERT INTO cakes VALUES(10, "pineapple", "yes", 3, 250);
INSERT INTO cakes VALUES(11, "apple pie", "no",1, 800);
INSERT INTO cakes VALUES(12, "Carrot cake", "yes",3, 250);
INSERT INTO cakes VALUES (13, "blACK CURRANT", "NO", 1, 250);
INSERT INTO cakes VALUES(14, "strawberry", "yes", 3, 600);
INSERT INTO cakes VALUES(15, "blueberry", "yes", 5, 380);
SELECT * FROM cakes GROUP BY price;
SELECT SUM(PRICE) FROM cakes;
